name: Website Deploy ⚡

on:
  # Allows triggering from another Workflow
  workflow_call:
    inputs:
      CLOUDFLARE_ACCOUNT_ID:
        type: string
        required: true
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      SHARED_GITHUB_TOKEN:
        required: true

  # Allows triggering manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy website - Cloudflare Pages ⚡
    steps:
      - name: Checkout ${{ github.ref_name }} 📥
        uses: actions/checkout@v4

      - name: Deploy website - Cloudflare Pages ⚡
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'ginetta-tonic-festival'
          directory: './src'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
