name: Pulumi 🔄

on:
  push:
    branches:
      - prod
      - develop
  workflow_dispatch:

env:
  # IMPORTANT! You must map the env vars for your providers here even though you add them as secrets in GitHub
  # See the setup page for providers here: https://www.pulumi.com/docs/intro/cloud-providers/
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: ginetta/ginetta-tonic-festival
  PULUMI_WORKING_DIRECTORY: ./infrastructure/
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

# Prevent concurrent releases
concurrency:
  group: websitedeployment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pulumi:
    runs-on: ubuntu-latest
    name: Pulumi
    steps:
      - name: Checkout ${{ github.ref_name }} 📥
        uses: actions/checkout@v4

      - name: Enable Corepack 📦
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.PULUMI_WORKING_DIRECTORY }}/package.json
          cache: yarn
          cache-dependency-path: ${{ env.PULUMI_WORKING_DIRECTORY }}/yarn.lock

      - name: Install Dependencies 📦
        run: yarn install --immutable
        working-directory: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: PR previews
        if: ${{ github.event_name == 'pull_request' }}
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: Apply infrastructure update 🚀
        if: ${{ github.event_name == 'push' }}
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}

  call-deployment-workflow:
    name: Deploy website - Cloudflare Pages ⚡
    needs: pulumi
    uses: ./.github/workflows/pages-deployment.yaml
    permissions:
      contents: read
      deployments: write
    with:
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      SHARED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
